### ISSUE TITLE
Introduce a "Resources tracker" utility

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#14]
## Summary

In this scope of this issue, we should introduce a new "Resources tracker" utility under Web Scraping utility umbrella. The bare minimum functionality should include:

* Utility should accept URL to any web page accessible by the Secutils.dev backend
* Utility should output URLs to all scripts, CSS files, images and video files that are loaded on the page within a predefined period after load
* Utility should allow user to configure timeout (default is TBD)

The following functionality should be available eventually, but not included in the initial scope:
* Utility should be able to tag scripts with "Framework" label (React, Vue etc.)
* Utility should be able to tag CSS with "Framework" (Tailwind etc.)
* Utility should be able to fetch and display resource content
* Utility should be able to store results and compare with new
* Utility should be able to periodically check for resource updates
```[tasklist]
### Tasks
- [x] Introduce new Web Scraper component - https://github.com/secutils-dev/secutils-web-scraper
- [x] Integrate API server with the Web Scraper component
- [x] Introduce new "Resources tracker" UIs in Web UI component
- [x] Update guides to include demos for "Resources tracker"
```

**Comment by azasypkin** [comment]
Resources tracker is released in [`1.0.0-alpha.2`](https://github.com/secutils-dev/secutils/releases/tag/v1.0.0-alpha.2)! Guides are available at https://secutils.dev/docs/guides/web_scraping/resources
