### ISSUE TITLE
Resources tracker utility should allow user to customize HTTP headers to access protected resources

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#18]
## Summary

In the context of https://github.com/secutils-dev/secutils/issues/14, we are planning to introduce a "Resources tracker" utility in Secutils.dev. This utility will enable the scraping of web resources from any publicly available web page.

To enhance the functionality of the utility, we need to consider allowing it to access web pages that are protected with authentication. This can be achieved if the protected pages support either HTTP authentication (via the `Authorization` HTTP header) or long-lived session cookies. To cater to these use cases, we would need to enable users to specify custom HTTP request headers as part of the tracker definition.

```[tasklist]
### Tasks
- [x] Update [Web Scraper](https://github.com/secutils-dev/secutils-web-scrapper) to support custom HTTP request headers
- [x] Update Web Resources Trackers APIs to accept custom HTTP request headers as a part of the tracker definition
- [x] Update [Web UI](https://github.com/secutils-dev/secutils-webui) to provide users with the tools to specify custom HTTP headers in the tracker editor UI
- [x] Update documentation to describe new functionality
```

**Comment by azasypkin** [comment]
Handled in https://github.com/secutils-dev/secutils/commit/83f48c08
