### ISSUE TITLE
Release 1.0.0-alpha.3

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#23]
## Summary

```[tasklist]
### Tasks
- [x] Bump and release new versions of https://github.com/secutils-dev/secutils-webui, https://github.com/secutils-dev/secutils-web-scrapper, and https://github.com/secutils-dev/secutils
- [x] Migrate `SelfSignedCertificate.key_algorigthm` to new format (https://github.com/secutils-dev/secutils/issues/8)
- [x] Update documentation to account for https://github.com/secutils-dev/secutils/issues/8. Done in https://github.com/secutils-dev/secutils-docs/commit/317240eb8bb1c4b6470d2b7de57dfe7339c94252.
- [x] Update documentation to account for https://github.com/secutils-dev/secutils/issues/19. Done in https://github.com/secutils-dev/secutils-docs/commit/8574256a90a224e76060cccc5aabe7df16bbc4ec.
- [x] Update documentation to account for https://github.com/secutils-dev/secutils/issues/20. Done in https://github.com/secutils-dev/secutils-docs/commit/8574256a90a224e76060cccc5aabe7df16bbc4ec.
```

**Comment by azasypkin** [comment]
The `v1.0.0-alpha.3` has been released https://github.com/secutils-dev/secutils/releases/tag/v1.0.0-alpha.3
