### ISSUE TITLE
Release 1.0.0-alpha.4

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#27]
## Summary

```[tasklist]
### Tasks
- [x] Bump and release new versions of https://github.com/secutils-dev/secutils-webui, https://github.com/secutils-dev/secutils-web-scrapper, and https://github.com/secutils-dev/secutils. Prepare release notes in GitHub and in the docs repository.
- [x] Migrate existing certificate templates to use new format of private key algorithm and separate table
- [x] Migrate existing web page resources trackers to use dedicated table
- [x] Document "subdomain" based webhook URL https://github.com/secutils-dev/secutils/issues/22
- [x] Document CSP import functionality https://github.com/secutils-dev/secutils/issues/16
- [x] Document "Private Keys" feature https://github.com/secutils-dev/secutils/commit/ae8a5814c3c85342f8a997186b4a930bea6327cc
- [x] Document newly added CSP directives (experimental and extensions)
- [x] Document CSP and certificate template share functionality https://github.com/secutils-dev/secutils/issues/24
- [x] Document "Web Scraping -> Content trackers" feature https://github.com/secutils-dev/secutils/issues/28
```

**Comment by azasypkin** [comment]
Done! 

__Check it out at https://secutils.dev!__

__Release notes:__ https://github.com/secutils-dev/secutils/releases/tag/v1.0.0-alpha.4
