### ISSUE TITLE
Release 1.0.0-alpha.5

### ISSUE THREAD

**Issue by azasypkin** [secutils-dev/secutils#35]
## Summary

```[tasklist]
### Tasks
- [x] Bump and release new versions of https://github.com/secutils-dev/secutils-webui, https://github.com/secutils-dev/secutils-web-scrapper, and https://github.com/secutils-dev/secutils. Prepare release notes in GitHub and in the docs repository. CONSIDER https://git-cliff.org/docs/ https://blog.orhun.dev/automated-rust-releases/
- [x] Clear responder request history table because of breaking change in the data format
- [x] Document new responder script/JS runtime functionality
```

**Comment by azasypkin** [comment]
Done! 

__Check it out at https://secutils.dev!__

__Release notes:__ https://github.com/secutils-dev/secutils/releases/tag/v1.0.0-alpha.5
